### PR TITLE
All APIM Entities via ARM Template

### PR DESCRIPTION
**Pull request by solankisamir**
- Fixed NSG Rule for Cache
- Add Support for Creating Backend, Certificate, API, Operation and Policies using ARM Template

### CODE REVIEW

**Comment by solankisamir** [comment]
@rwike77 @vturecek can you take a look ?

**Comment by solankisamir** [comment]
@rwike77  @vturecek  ping on this.

**Comment by solankisamir** [comment]
@rwike77 a gentle nudge on this. Should we add the template someplace else?

**Comment by rwike77** [comment]
@solankisamir I'm starting to try out the new template.  I also need to update the associated article, will try to do that in the next day or two.  Sorry for the delay.

**Comment by solankisamir** [comment]
Closing the pull request, as changes have been incorporated.

**Pull request closed without merging**
